### ISSUE TITLE
项目能在CPU环境运行吗

### ISSUE THREAD

**Issue by w-Bro** [MhLiao/MaskTextSpotterV3#13]
如果可以，需要修改哪些地方呢？

**Comment by MhLiao** [comment]
@w-Bro 可以尝试cfg.MODEL.DEVICE设置为“cpu”，但是我没有验证过。

**Comment by nmber5** [comment]
> 如果可以，需要修改哪些地方呢？



> @w-Bro 可以尝试cfg.MODEL.DEVICE设置为“cpu”，但是我没有验证过。

有验证成功吗？
