### ISSUE TITLE
关于检测gt的一个疑问

### ISSUE THREAD

**Issue by yyr6661** [MhLiao/MaskTextSpotterV3#14]
感谢作者大大分享！

我现在想训练一个中文模型，使用的是几个开源数据集，其中包含了扭曲文本
请问模型只能接受矩形box作为输入吗？扭曲文本的多边形points标记要怎么转换成模型能接受的gt格式呢？
是转换成最小外接矩形还是需要单字坐标标记？

**Comment by yyr6661** [comment]
我目前将points转换成最小外接矩形训练得到的模型完全不能识别到字符。。。

**Comment by MhLiao** [comment]
@yyr6661 中文跟英文的字符类别完全不一样，需要修改代码，包括data loader和识别gt的生成。
