### ISSUE TITLE
Error when training on scut-eng-char_train dataset

### ISSUE THREAD

**Issue by ZhengWei0918** [MhLiao/MaskTextSpotterV3#15]
There will always be an error when training on scut-eng-char_train dataset downloaded from README.

> Traceback (most recent call last):
>   File "tools/train_net.py", line 153, in <module>
>     main()
>   File "tools/train_net.py", line 149, in main
>     model = train(cfg, args.local_rank, args.distributed)
>   File "tools/train_net.py", line 87, in train
>     local_rank,
>   File "/data/maskTextSpotter/maskrcnn_benchmark/engine/trainer.py", line 69, in do_train
>     loss_dict = model(images, targets)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/_initialize.py", line 197, in new_fwd
>     **applier(kwargs, input_caster))
>   File "/data/maskTextSpotter/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 82, in forward
>     x, result, detector_losses = self.roi_heads(fuse_feature, proposals, targets)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/maskTextSpotter/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 24, in forward
>     x, detections, loss_box = self.box(features, proposals, targets)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/maskTextSpotter/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py", line 47, in forward
>     x = self.feature_extractor(features, proposals)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/maskTextSpotter/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_feature_extractors.py", line 169, in forward
>     x = self.feature_mask(x, proposals)
>   File "/data/maskTextSpotter/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_feature_extractors.py", line 146, in feature_mask
>     masks = torch.stack(masks, dim=0)
> **RuntimeError: Expected object of scalar type Byte but got scalar type Bool for sequence element 932 in sequence argument at position #1 'tensors'**
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
>     main()
>   File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
>     cmd=cmd)
> subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/pretrain/seg_rec_poly_fuse_feature.yaml']' returned non-zero exit status 1.

The bold text indicates the dtype is Boolean but not Byte, then I try to dubug to show the data
(I modified the code so the line number may be different)

And I print some debug info in `feature_mask` function in `roi_box_feature_extractors.py`:

```
        for proposal in proposals:
            segmentation_masks = proposal.get_field("masks")
            boxes = proposal.bbox.to(torch.device("cpu"))
            for segmentation_mask, box in zip(segmentation_masks, boxes):
                cropped_mask = segmentation_mask.crop(box)

                scaled_mask = cropped_mask.resize((self.cfg.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION, self.cfg.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION))

                mask = scaled_mask.convert(mode="mask")
                if mask.dtype != torch.uint8:
                    print(segmentation_mask)
                    print('+' * 20)
                    print(box)
                    print('#' * 20)
                    print(cropped_mask)
                    print('*' * 20)
                    print(scaled_mask)
                    print('=' * 20)
                    print(mask)
                    print('-' * 20)
                masks.append(mask)
```

When the error occurs, the printed info is:

```
Polygons(num_polygons=1, image_width=900, image_height=600, mode=None)
++++++++++++++++++++
tensor([270., 599., 363., 599.])
####################
Polygons(num_polygons=1, image_width=93.0, image_height=1, mode=None)
********************
Polygons(num_polygons=1, image_width=7, image_height=7, mode=None)
====================
tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])
--------------------

```

Apparently, the last tensor's dtype is not what we want, we want a tensor in `torch.uint8` dtype, but it is boolean.
So how does this happen? 

Thanks

**Comment by MhLiao** [comment]
@ZhengWei0918 What's your PyTorch version? Please try PyTorch 1.4 if not.

**Comment by ZhengWei0918** [comment]
Thanks for your reply, my python is 3.7.4, pytorch version is 1.4.0, and some key packages' version: 

Shapely                1.7.0
opencv-python          3.4.4.19
numpy                  1.17.4

The stange thing is, it runs properly in the beginning, for example, the beginning 120 iters are **all** normal like this:
```
tensor([[0, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 0],
        [0, 1, 1, 1, 1, 1, 1],
        [0, 0, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 0]], dtype=torch.uint8)
```
But when the problem occurs, it turns into this:
```
tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])
```
Then the program crashes and stops.
So if you have never encountered this problem (my code and data is the same as yours), I have to check all packages' version.

Thanks

**Comment by MhLiao** [comment]
@ZhengWei0918 I guess this problem is [here](https://github.com/MhLiao/MaskTextSpotterV3/blob/8fbb054588d7adf6afdd287637db5c25062a764f/maskrcnn_benchmark/structures/segmentation_mask.py#L297). You can change the `dtype` from `torch.bool` to`torch.uint8`.

**Comment by ZhengWei0918** [comment]
@MhLiao Thank you, the problem has been fixed. Maybe I am not famaliar enough with the MaskRcnn's code. Thank you!

**Comment by lcsama** [comment]
@MhLiao I have noticed this issue. I checked all the tensor dtype and made a pull request to fix it. #9

**Comment by MhLiao** [comment]
@lcsama Great! Thanks for your PR and it is merged.
