### ISSUE TITLE
字典问题

### ISSUE THREAD

**Issue by cylzty110** [MhLiao/MaskTextSpotterV3#16]
代码里面使用的字典和官方比赛提供的有啥区别？对结果影响大么

**Comment by MhLiao** [comment]
字典主要进行了两个操作：（1）加入gt中有而原词典中没有的词 （只是简单做了一个遍历，没有统计这种词是否存在或者存在多少，理想情况下应该不存在）（2）生成word pair：由于模型并没有加入特殊字符类别比如标点符号，所以我们将字典中的词的特殊字符去掉作为生成其对应的word pair，以方便做edit distance匹配。
我觉得影响应该不大，你可以试试对比一下。

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by cylzty110** [comment]
复现的过程中还有一个问题，就是masktextspotterv3只生成数字和字母，那么针对total-text数据集none指标，若gt中存在特殊字符，该如何处理？

**Comment by MhLiao** [comment]
@cylzty110 我们在匹配判断的时候会将gt中的特殊字符去掉
