### ISSUE TITLE
CHAR_NUM_CLASSES and NUM_CHAR can not be changed due to a bug

### ISSUE THREAD

**Issue by yudai09** [MhLiao/MaskTextSpotterV3#21]
CUDA assertion error occurred when I tried to change the number for CHAR_NUM_CLASSES and NUM_CHAR.
I have fixed the error by changing magic numbers, 37 and 38, from `maskrcnn_benchmark/structures/segmentation_mask.py`.
I think it’s better to fix this bug by replacing those magic numbers by the number from config files.

**Comment by MhLiao** [comment]
@yudai09 Thanks for your suggestion. I fixed it.

**Comment by yudai09** [comment]
@MhLiao I have checked [the commit](https://github.com/MhLiao/MaskTextSpotterV3/commit/9bd595e40c693ced0dc8ce4f33d65048424189e5). thank you so much:)
