### ISSUE TITLE
slow testing speed on ICDAR2015

### ISSUE THREAD

**Issue by thcheung** [MhLiao/MaskTextSpotterV3#22]
I followed the readme file on this repo. However, the testing speed is a bit slow. During testing of ICDAR2015, each image takes around 18~19s to finish, which is very slow compared to the mentioned 
FPS in the paper. I used the command nvidia-smi and ensures that the GPU is running. Does it really take 18s/image for anyone?

Remark: I used the config provided in the repo.

### Hardware
CPU: Intel® Core™ i9-9900K CPU @ 3.60GHz × 16
Memory: 62.7 GB
GPU: GeForce RTX 2080 Ti

### Software
Ubuntu 18.04
Python: 3.8
Pytorch: 1.4.0
Torchvision: 0.5.0
Cuda: 10.1

**Comment by josaphattirza** [comment]
can you share any information on how you tackle this problem? I face the same problem now, thankyou!
