### ISSUE TITLE
Where is the ground truth labels for the ICDAR2015 testset

### ISSUE THREAD

**Issue by honglongcai** [MhLiao/MaskTextSpotterV3#29]
Hello @MhLiao , I didn't find the ground truth labels for ICDAR2015 testset in the provided google drive link. There are only test_images, test_list.txt, train_images, train_list.txt, and train_gts in the ICDAR2015 dataset link. How to evaluate the model on ICDAR2015 if we don't have test ground truth labels in the dataset?

**Comment by MhLiao** [comment]
@honglongcai Test labels are provided in the evaluation directory, which is named as "gt.zip".

**Comment by honglongcai** [comment]
Got it, thanks!
