### ISSUE TITLE
Does it work for Chinese characters?

### ISSUE THREAD

**Issue by jjjjohnson** [MhLiao/MaskTextSpotterV3#5]
Thanks for the great work! As the Character Segmentation branch only has 37 (36 for alphanumeric characters and 1 for the background) classes, I wonder if it still woks when applies 6000+ Chinese characters. Might not have character level annotation Chinese dataset....

**Comment by MhLiao** [comment]
@jjjjohnson You can remove/disable the character segmentation branch for Chinese characters, as done in Mask TextSpotter v2 for the MLT dataset.

**Comment by oszn** [comment]
> character segmentation branch

i cant find v2,in the v3 version i did like u said, to disable the char_mask_on,but the seqcharmaskrccn4predictor will throw a error,should i choose another predictor?
