### ISSUE TITLE
我在评估total_text数据集时出现了zip错误

### ISSUE THREAD

**Issue by sheyuwei** [MhLiao/MaskTextSpotterV3#55]
zip error: Nothing to do! (try: zip -r -q -j ./cache_files/0.05_0.5_over0.2.zip . -i ./cache_files/0.05_0.5_0.9)
Error!
Error loading the ZIP archive

请问可以帮忙解决一下吗？谢谢，我的邮箱是624810276@qq.com

**Comment by jingyj203** [comment]
我也遇到了一样的问题，请问你解决了吗

**Comment by InitGo** [comment]
我也遇到了一样的问题，蹲一个解决方案
