### ISSUE TITLE
中文检测

### ISSUE THREAD

**Issue by yanmeizhao** [MhLiao/MaskTextSpotterV3#8]
我看到展现的例子很多英文的，请问能检测中文嘛？

**Comment by MhLiao** [comment]
可以，不过你需要用中文数据集训练

**Comment by carolyueyueyue** [comment]
![2022-08-07 17-41-01 的屏幕截图](https://user-images.githubusercontent.com/86870014/183284963-2ce8d86a-1aac-42d5-b8ef-a7b78dc7ece8.png)，我在训练中文数据集时发现的问题，self.char_classes='0123456789abcdefghijklmnopqrstuvwxyz'这个需要怎样修改？希望得到您的回答

**Comment by ChuanyangGong** [comment]
> 

我觉得这里应该是换成自己的中文字符集，他的文本识别最后其实就是一个分类问题，但是我在修改了文件去 train 中文数据的时候直接爆显存了，CUDA out of memory。我感觉这个模型太大了，train 英文的时候用 8 卡 train，单张卡上只能跑一张图才能稳定不爆显存，这个模型不精简掉东西很难直接用来train中文的。不知道有没有兄弟成功了

**Comment by carolyueyueyue** [comment]
> 

你测试的中问数据集是公开的还是自己制作的？看你说的是有开始训练了？但是因为内存导致训练不成功？
